version: '2.4'
services:
  frontend:
    image: taskmanager/client
    ports:
      - "80:80"
    environment:
      REACT_APP_BACKEND: http://localhost:5000/api
    restart: always
  api:
    image: taskmanager/api
    environment:
      DB_NAME: taskmanagerDB
      DB_USER: user
      DB_HOST: db
      DB_PASSWORD: pass
      DB_PORT: 5432
      JWT_KEY: this_is_my_supersecret_key
    ports:
      - "5000:5000"
    restart: always
  db:
    image: taskmanager/db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: taskmanagerDB
    restart: always
    volumes:
      - /var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    restart: always